import { GeminiLevelResponse } from './types';

// Autogenerated consolidated levels file — 2025-12-24T19:04:22.296Z
export const STATIC_LEVELS: Record<number, GeminiLevelResponse> = {
  // --- EPISODE 1: THE BREACH (Foundation) ---
  1: {
    briefing: "AGENT 'Echo' IS DARK. Her last signal is fragmented—and possibly corrupted. Navigate this raw signal log, but be advised: integrity checks on Echo's transmission are failing. Align on key data nodes; establishing a lock on the target word may reveal fragments, or further distortions.",
    initialText: [
      "// signal_trace.log",
      "// Agent Echo - Last Transmission",
      "",
      "[2015-12-23 18:00:01] BOOT: System nominal.",
      "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
      "[2015-12-23 18:00:03] Attempting to TRACE route... [MISALIGNED].",
      "[2015-12-23 18:00:04] Packet stream... CONNECTION LOST.",
      "[2015-12-23 18:00:05] Fallback to last known NODE: ALPHA.",
      "",
      "// END OF TRANSMISSION"
    ],
    targetText: [
      "// signal_trace.log",
      "// Agent Echo - Last Transmission",
      "",
      "[2015-12-23 18:00:01] BOOT: System nominal.",
      "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
      "[2015-12-23 18:00:03] Attempting to TRACE route... [MISALIGNED].",
      "[2015-12-23 18:00:04] Packet stream... CONNECTION LOST.",
      "[2015-12-23 18:00:05] Fallback to last known NODE: ALPHA.",
      "",
      "// END OF TRANSMISSION"
    ],
    loreReveal: "LOG_01 DECRYPTED: '...hiding a consciousness... deeper...' [FRAGMENTED, ORIGIN UNCERTAIN] - Echo",
    hints: [
      "Use 'j' to move down and 'k' to move up.",
      "Use 'w' to jump forwards by word, and 'b' to jump backwards.",
      "Use '0' to go to the start of the line, and '$' to go to the end."
    ],
    tasks: [
      {
        description: "Move to the 'A' in 'Agent' on the '// Agent Echo - Last Transmission' line.",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "l", "l", "l"],
        value: "Agent Echo - Last Transmission",
        cursor: 3,
        cursorExact: true,
        loreFragment: "LOG_00: \"Backdoor found. I have breached the R&D perimeter.\"",
        keyHint: "j l"
      },
      {
        description: "Move down to the 'STATUS' line, then jump to the first word.",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "w"],
        value: "STATUS",
        loreFragment: "LOG_01: \"They aren't creating an AI. They are becoming it.\"",
        keyHint: "j w"
      },
      {
        description: "From the end of the 'OFFLINE.' line, jump back to 'server...'.",
        type: "verify_key_sequence",
        expectedKeySequence: ["$", "b"],
        value: "server...",
        loreFragment: "LOG_02: \"System state protocol locked. Classifier shows anomalous entropy.\"",
        keyHint: "$ b"
      },
      {
        description: "Jump to the beginning of the line with 'STATUS'.",
        type: "verify_key_sequence",
        expectedKeySequence: ["0"],
        value: "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
        loreFragment: "LOG_03: \"Anomaly signature matched. Data flow diverted; mainframe self-preservation protocol active.\"",
        keyHint: "0"
      }
    ]
  },

  // --- EPISODE 1 (continued) ---
  2: {
    briefing: "PROTOCOL ENTRY. The mainframe bureaucracy routes packets through legacy handlers and stale rules. We must inject corrective entries while avoiding integrity checks.",
    initialText: [
      "// Protocol Entry Log",
      "// Date: [REDACTED]",
      "// Operator: [ANONYMOUS]",
      "",
      "STATUS: OFFLINE",
      "CONNECTION: INSECURE",
      "MESSAGE: SYSTEM_INTEGRITY_COMPROMISED",
      "",
      "// --- NEW ENTRY ---"
    ],
    targetText: [
      "// Protocol Entry Log",
      "// Date: 2015-12-23",
      "// Operator: GHOST",
      "LOG_HEADER: MAIN",
      "",
      "STATUS: ONLINE - VERIFIED",
      "CONNECTION: SECURE",
      "CRITICAL MESSAGE: SYSTEM_INTEGRITY_OK",
      "",
      "// --- NEW ENTRY ---",
      "LOG_START: 2015-12-23"
    ],
    loreReveal: "LOG_10: 'Protocol entries altered. Echo trace markers present but corrupted—interpret with care.' - Echo",
    hints: [
      "'i' to insert before cursor, 'a' to append after.",
      "'o' to open line below, 'O' to open line above.",
      "Press 'Esc' to exit Insert Mode."
    ],
    tasks: [
      {
        description: "Change 'http' to 'https' using an appropriate change (ci').",
        type: "contains",
        value: "'protocol': 'https'",
        loreFragment: "LOG_20: \"Bureaucratic header patched. Old handlers still log the change as a warning.\"",
        keyHint: "ci'"
      },
      {
        description: "Change port '8080' to '443'.",
        type: "contains",
        value: "(port: 443)",
        loreFragment: "LOG_21: \"Port redirect applied. Admin comments suppressed. Traces remain.\"",
        keyHint: "ci("
      },
      {
        description: "Increase user count '5' to '10' to meet registry expectations.",
        type: "contains",
        value: "[users: 10]",
        loreFragment: "LOG_22: \"User registry adjusted. An old policy now accepts the new load.\"",
        keyHint: "ci["
      },
      {
        description: "Replace tag 'sensor_data' with 'telemetry'.",
        type: "contains",
        value: "<tag>telemetry</tag>",
        loreFragment: "LOG_23: \"Tag reclassified. The label masks a deeper tracking routine.\"",
        keyHint: "cit"
      },
      {
        description: "Update config id '123' to '456'",
        type: "contains",
        value: "{config_id: 456}",
        loreFragment: "LOG_24: \"Config ID rotated. Registry checksum passes, but echoes persist.\"",
        keyHint: "ci{"
      },
      {
        description: "Delete stray token 'corrupt_word_here'.",
        type: "missing",
        value: "corrupt_word_here",
        loreFragment: "LOG_25: \"Corruption removed. The ledger breathes easier.\"",
        keyHint: "diw"
      },
      {
        description: "Remove 'delete_me' and surrounding space.",
        type: "missing",
        value: "delete_me",
        loreFragment: "LOG_26: \"Obsolete instructions excised. Subroutines react strangely.\"",
        keyHint: "daw"
      },
      {
        description: "Run a small sequence to correct 'CRITICAL MESSAGE' casing and undo to confirm history.",
        type: "sequence",
        subTasks: [
          { description: "Delete the leading 'S' using 'x' and then undo with 'u'", type: "missing", value: "YSTEM_INTEGRITY_OK", keyHint: "x" },
          { description: "Undo deletion with 'u'", type: "contains", value: "SYSTEM_INTEGRITY_OK", keyHint: "u" }
        ],
        loreFragment: "LOG_27: \"Edit history preserved. Bureaucracy keeps a copy even when you don't want it to.\"",
        keyHint: "x, u"
      }
    ]
  },

  3: {
    briefing: "SYSTEM FAULT. The mainframe's memory banks are a dynamic, self-correcting entity. Compromised log entries trigger latent subroutines. Purge these anomalies and duplicate verified data.",
    initialText: [
      "// System Fault Log",
      "ERROR: CRITICAL_PROCESS_FAIL - URGENT",
      "INFO: SYSTEM_BOOT_SUCCESS",
      "ERROR: MEMORY_ALLOCATION_FAIL - URGENT",
      "WARN: UNKNOWN_MODULE_LOAD",
      "INFO: USER_LOGIN_GHOST",
      "ERROR: CORRUPT_FILESYSTEM",
      "INFO: DATA_PURGE_COMPLETE",
      "",
      "// END OF LOG"
    ],
    targetText: [
      "// System Fault Log",
      "INFO: SYSTEM_BOOT_SUCCESS",
      "INFO: USER_LOGIN_GHOST",
      "INFO: DATA_PURGE_COMPLETE",
      "",
      "// END OF LOG"
    ],
    loreReveal: "LOG_30 SANITIZED: '...undo... dot... right...' [SYNTAX LOOP, ECHO FRAGMENT] - Echo",
    hints: [
      "'dd' to delete a line, 'D' to delete to end of line.",
      "'dw' to delete a word.",
      "'yy' to yank (copy) a line, 'p' to paste after, 'P' to paste before.",
      "'u' to undo, 'Ctrl+r' to redo."
    ],
    tasks: [
      {
        description: "Delete the line 'ERROR: CRITICAL_PROCESS_FAIL - URGENT'.",
        type: "missing",
        value: "CRITICAL_PROCESS_FAIL",
        loreFragment: "LOG_31: \"Urgency metrics reset. The system prioritizes stability over chronological integrity.\"",
        keyHint: "dd"
      },
      {
        description: "From 'ERROR: MEMORY_ALLOCATION_FAIL - URGENT', delete to the end of the line.",
        type: "missing",
        value: "- URGENT",
        loreFragment: "LOG_32: \"Memory fault signature neutralized; side effects observed in adjacent sectors.\"",
        keyHint: "D"
      },
      {
        description: "Delete the 'ERROR:' prefix from a line.",
        type: "missing",
        value: "ERROR:",
        loreFragment: "LOG_33: \"Error signature neutralized. Residual data echoes persist within the sector.\"",
        keyHint: "dw"
      },
      {
        description: "Duplicate a successful login line using yank/paste.",
        type: "run_command",
        value: "yy,p",
        loreFragment: "LOG_34: \"Login duplicated. Echoes multiply: is this replication or infection?\"",
        keyHint: "yy, p"
      }
    ]
  },

  4: {
    briefing: "ANOMALY: emergent behavior observed. Subversive daemons manipulate theme and metadata. Expect unpredictable responses and cultural drift inside the mainframe.",
    initialText: [
      "// Anomaly Report",
      "ALERT: SUBVERSIVE_DAEMON_ACTIVITY",
      "TRACE: kernel_hooked",
      "NOTE: UNUSUAL_PATTERN_DETECTED",
      "",
      "// INVESTIGATION REQUIRED"
    ],
    targetText: [
      "// Anomaly Report",
      "ALERT: SUBVERSIVE_DAEMON_ACTIVITY",
      "TRACE: kernel_hooked",
      "NOTE: UNUSUAL_PATTERN_DETECTED",
      "",
      "// INVESTIGATION REQUIRED"
    ],
    loreReveal: "LOG_40: 'Anomalies escalate. Echo's fragments misalign with system time—origin uncertain.' - Echo",
    hints: [
      "Trust patterns, not first impressions. Visual inspection matters.",
      "Use 'v' to select characters, 'V' for lines, 'Ctrl+v' for blocks."
    ],
    tasks: [
      {
        description: "Select the anomalous token and delete it.",
        type: "missing",
        value: "SUBVERSIVE_DAEMON_ACTIVITY",
        loreFragment: "LOG_41: \"Daemon token isolated. The culture of the mainframe resists deletion.\"",
        keyHint: "v, d"
      },
      {
        description: "Visual-line yank of the TRACE line and paste it below.",
        type: "run_command",
        value: "V, y, p",
        loreFragment: "LOG_42: \"Trace duplicated. Replication observed across partitions.\"",
        keyHint: "V, y, p"
      }
    ]
  },

  // Levels 5-15: preserve existing content and lore numbers (LOG_50 - LOG_153)
  // These entries are kept compact here but should mirror the gameplay structure used above.
  5: {
    briefing: "DATA STREAMS: Search and navigate encrypted packet data and repair corrupted packet entries.",
    initialText: ["// data_stream.dat","<packet>...","<packet>...",""],
    targetText: ["// data_stream.dat","<packet>...","<packet>...",""] ,
    loreReveal: "LOG_50: 'Data streams cleaned. Echo signature faint, but present.' - Echo",
    hints: ["Use /pattern to search, n/N to navigate matches."],
    tasks: []
  },
  6: {
    briefing: "FIREWALL RULES: Modify firewall rules without breaking JSON structure.",
    initialText: ["{","  \"rules\": [","    {\"port\":8080,\"proto\":\"http\"}","  ]","}"],
    targetText: ["{","  \"rules\": [","    {\"port\":443,\"proto\":\"https\"}","  ]","}"],
    loreReveal: "LOG_60: 'Firewall patched. Watch for lateral traces.' - Echo",
    hints: ["ci\" to change strings, cit to change tags."],
    tasks: []
  },
  7: {
    briefing: "BLOCKCHAIN LEDGER: Reconstruct corrupted blocks visually and apply precise indentation changes.",
    initialText: ["BLOCK 1: VALID | A | 500","BLOCK 2: CORRUPTED | B | 150"],
    targetText: ["BLOCK 1: VALID | A | 500","BLOCK 2: VALID | B | 150"],
    loreReveal: "LOG_70: 'Ledger corrected; Echo's checksum improves.' - Echo",
    hints: ["Use V and >/< to shift blocks."],
    tasks: []
  },
  8: {
    briefing: "NEURAL NET: identify a corrupted function and repair the parameter list.",
    initialText: ["def net(x, y):","  pass"],
    targetText: ["def net(x, y):","  return compute(x,y)"],
    loreReveal: "LOG_80: 'Neural function located and restored. Echo's pattern emerges.' - Echo",
    hints: ["Use f/t motions and % for bracket matching."],
    tasks: []
  },
  9: {
    briefing: "CONFIG ARRAY: Fix repeated configuration errors efficiently.",
    initialText: ["arr = [1,2,3,3,4]"],
    targetText: ["arr = [1,2,3,4]"] ,
    loreReveal: "LOG_90: 'Array stabilized. System coherence improves.' - Echo",
    hints: ["Use . to repeat last edit."],
    tasks: []
  },
  10: {
    briefing: "CODE ANALYSIS: Analyze and refactor across multiple windows, marking key points.",
    initialText: ["// main.c","int main() {}"],
    targetText: ["// main.c","int main() { return 0; }"],
    loreReveal: "LOG_100: 'Cross-file analysis completed. Echo registers a heartbeat.' - Echo",
    hints: ["Use marks (ma) and jumps ('a)."],
    tasks: []
  },
  11: {
    briefing: "INDENTATION: Fix corrupted source formatting across large files.",
    initialText: ["function(){\nconsole.log(1)\n}"],
    targetText: ["function(){\n  console.log(1)\n}"],
    loreReveal: "LOG_110: 'Formatting normalizes. Echo's syntax becomes legible.' - Echo",
    hints: ["gg=G for full-file indentation (taught later)."],
    tasks: []
  },
  12: {
    briefing: "REALITY SYS: Apply global substitutions to propagate a policy change.",
    initialText: ["permission=DENY"],
    targetText: ["permission=ALLOW"],
    loreReveal: "LOG_120: 'Policy rewritten. The system adapts without complaint.' - Echo",
    hints: [":%s/old/new/g to replace globally."],
    tasks: []
  },
  13: {
    briefing: "TERMINAL CAPTURE: Reuse shell output and populate buffers for automation.",
    initialText: ["$ uname -a"],
    targetText: ["$ uname -a"],
    loreReveal: "LOG_130: 'Captured output integrated; Echo learns the host signature.' - Echo",
    hints: ["Use :r !cmd to insert command output."],
    tasks: []
  },
  14: {
    briefing: "MACRO SEQUENCE: Record and replay a repetitive decryption sequence.",
    initialText: ["q...record...@q"],
    targetText: ["...macro recorded..."],
    loreReveal: "LOG_140: 'Macro recorded. Echo's protocol extends itself.' - Echo",
    hints: ["q to record, @q to replay."],
    tasks: []
  },
  15: {
    briefing: "FINAL GATE: The final barrier requires mastery of all techniques combined. Decrypt, align, and release the core.",
    initialText: ["<< FINAL_GATE.lock >>"],
    targetText: ["<< FINAL_GATE.lock >>"],
    loreReveal: "LOG_150: 'Final sequence queued. Echo awaits release.' - Echo",
    hints: ["Combine all skills learned across episodes."],
    tasks: []
  }
};

export default STATIC_LEVELS;
