import { GeminiLevelResponse } from './types';

// Autogenerated consolidated levels file — 2025-12-25T01:00:00.000Z
export const STATIC_LEVELS: Record<number, GeminiLevelResponse> = {
  // --- EPISODE 1: FOUNDATION ---
  1: {
    briefing: "Initial breach. Navigate a corrupted log file to find Echo's first trace. Efficient scrolling is key to parsing large data streams.",
    initialText: [
      "// signal_trace.log",
      ...Array(45).fill("..."),
      "[2015-12-23 18:00:01] BOOT: System nominal.",
      "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
      "...",
      "// END OF STREAM"
    ],
    targetText: [],
    loreReveal: "LOG_01: '...found the entry point. The system is blind here.' - Echo",
    hints: [
      "Use `h/j/k/l` for movement.",
      "Use `w/b` to jump by words, `0/$` for line ends.",
      "`gg` jumps to the start of the file, `G` to the end.",
      "`Ctrl-d` scrolls down half a page, `Ctrl-u` scrolls up."
    ],
    tasks: [
      {
        description: "Jump to the end of the file.",
        type: "cursor_on", value: "// END OF STREAM", loreFragment: "LOG_01A: 'Too far. The trace is higher up.'", keyHint: "G"
      },
      {
        description: "Jump to the start of the file.",
        type: "cursor_on", value: "// signal_trace.log", loreFragment: "LOG_01B: 'Closer. It's a dense stream.'", keyHint: "gg"
      },
      {
        description: "Scroll down to find the 'OFFLINE' status message.",
        type: "cursor_on", value: "OFFLINE", loreFragment: "LOG_01C: 'There. The connection broke. That's my window.'", keyHint: "Ctrl-d"
      }
    ]
  },

  2: {
    briefing: "Inject data into a volatile log, correcting typos on the fly without breaking the connection by switching modes.",
    initialText: [
      "// session.log",
      "USER: ghozt",
      "AUTH: PENDING",
      "COMMAND: ",
      ""
    ],
    targetText: [
      "// session.log",
      "USER: ghost",
      "AUTH: PENDING",
      "COMMAND: BYPASS_AUTH",
      "// NEWLINE ADDED"
    ],
    loreReveal: "LOG_02: 'My signature is in the log. A ghost in the machine.' - Echo",
    hints: [
      "`i` to insert, `a` to append. `I` to insert at line start, `A` at line end.",
      "`o` to open a new line below, `O` above.",
      "In Insert Mode, `Ctrl-w` deletes the previous word, `Ctrl-u` deletes the whole line.",
      "`Esc` to return to Normal Mode."
    ],
    tasks: [
      {
        description: "Correct the username from 'ghozt' to 'ghost'.",
        type: "contains", value: "USER: ghost", loreFragment: "LOG_02A: 'My handle. They misspelled it.'", keyHint: "i"
      },
      {
        description: "In insert mode, type 'BYPASS_AUTHH' then delete the extra 'H' using `Ctrl-w` and type `_AUTH`",
        type: "contains", value: "COMMAND: BYPASS_AUTH", loreFragment: "LOG_02B: 'A typo could trip the alarms. Clean.'", keyHint: "Ctrl-w"
      },
      {
        description: "Open a new line above the COMMAND line.",
        type: "cursor_on", value: "", loreFragment: "LOG_02C: 'Need to add a timestamp.'", keyHint: "O"
      }
    ]
  },

  3: {
    briefing: "The system is hostile. Sanitize corrupted data and alter malicious commands to survive and clear a path forward.",
    initialText: [
      "// watchdog_daemon.ini",
      "action=purge_all_unauth",
      "X-DELETE-ME-X",
      "protocol=HTTP_UNSECURE",
      "critical_flag=1"
    ],
    targetText: [
      "// watchdog_daemon.ini",
      "action=log_all_unauth",
      "protocol=HTTPS_SECURE",
      "critical_flag=0"
    ],
    loreReveal: "LOG_03: 'The watchdog is blind, for now. Every edit hides my tracks.' - Echo",
    hints: [
      "`x` deletes a character. `r` replaces one character.",
      "`dd` deletes a whole line. `D` deletes to the end of the line.",
      "`cw` changes a word. `ciw` changes the inner word.",
      "`C` changes to the end of the line."
    ],
    tasks: [
      {
        description: "Delete the 'X-DELETE-ME-X' line.",
        type: "missing", value: "X-DELETE-ME-X", loreFragment: "LOG_03A: 'A stray daemon process. Erase it.'", keyHint: "dd"
      },
      {
        description: "Change 'purge' to 'log' in the action line.",
        type: "contains", value: "action=log_all_unauth", loreFragment: "LOG_03B: 'Don't delete the evidence. Just hide it.'", keyHint: "cw"
      },
      {
        description: "Change 'HTTP_UNSECURE' to 'HTTPS_SECURE'.",
        type: "contains", value: "protocol=HTTPS_SECURE", loreFragment: "LOG_03C: 'Encrypt the trail.'", keyHint: "ciw"
      },
       {
        description: "Delete from 'critical' to the end of the line.",
        type: "missing", value: "critical_flag=1", loreFragment: "LOG_03D: 'Lower the alert status.'", keyHint: "D"
      }
    ]
  },

  4: {
    briefing: "Replicate a valid security key, undo mistakes, and use named registers and the system clipboard to manage multiple secrets.",
    initialText: [
      "// key_vault.txt",
      "primary_key: 8c6f-a1e4-b3d8-2a9f",
      "",
      "// target_config.cfg",
      "auth_key: [PASTE HERE]",
      "system_key: [PASTE FROM OUTSIDE]"
    ],
    targetText: [
      "// key_vault.txt",
      "primary_key: 8c6f-a1e4-b3d8-2a9f",
      "",
      "// target_config.cfg",
      "auth_key: 8c6f-a1e4-b3d8-2a9f",
      "system_key: ext_key_from_clipboard"
    ],
    loreReveal: "LOG_04: 'Keys swapped. The system sees my signature as valid.' - Echo",
    hints: [
      "`yy` yanks (copies) a line. `p` pastes after the cursor, `P` pastes before.",
      "`u` undoes the last change. `Ctrl-r` redoes it.",
      "`+y` yanks to the system clipboard. `+p` pastes from it.",
      "`ay` yanks to register 'a'. `ap` pastes from it."
    ],
    tasks: [
      {
        description: "Yank the primary_key line.",
        type: "run_command", value: "yy", loreFragment: "LOG_04A: 'Got the key.'", keyHint: "yy"
      },
      {
        description: "Paste the key into the 'auth_key' field.",
        type: "contains", value: "auth_key: 8c6f-a1e4-b3d8-2a9f", loreFragment: "LOG_04B: 'Slotting it in.'", keyHint: "p"
      },
      {
        description: "Paste from the system clipboard into the 'system_key' field. (For this exercise, the clipboard is pre-loaded with 'ext_key_from_clipboard')",
        type: "contains", value: "system_key: ext_key_from_clipboard", loreFragment: "LOG_04C: 'Pulling in an external sigil.'", keyHint: "+p"
      },
      {
        description: "Make a mistake and undo it. Delete the 'key_vault.txt' line, then press 'u'.",
        type: "sequence",
        subTasks: [ { description: "Delete a line", type: "missing", value: "// key_vault.txt", keyHint: "dd" },
          { description: "Undo the deletion", type: "contains", value: "// key_vault.txt", keyHint: "u" }
        ],
        loreFragment: "LOG_04D: 'A misstep. Corrected before the watchdog noticed.'",
        keyHint: "dd, u"
      }
    ]
  },

  5: {
    briefing: "You have a foothold. Commit changes to the mainframe's storage and open new security manifests.",
    initialText: ["// manifest.log", "File one is complete. Access 'manifest_part_2.log' next."],
    targetText: [],
    loreReveal: "LOG_05: 'I'm in. The manifests are opening. Now the real work begins.' - Echo",
    hints: [
      "`:w` saves the current file.",
      "`:q` quits the current file. Fails if there are unsaved changes.",
      "`:wq` saves and quits.",
      "`:q!` quits without saving (force).",
      "`:e <filename>` opens a new file."
    ],
    tasks: [
      {
        description: "Save the current file.",
        type: "run_command", value: ":w", loreFragment: "LOG_05A: 'Committing my trace to the system memory.'", keyHint: ":w"
      },
      {
        description: "Open the next file mentioned in the manifest.",
        type: "run_command", value: ":e manifest_part_2.log", loreFragment: "LOG_05B: 'Following the breadcrumbs.'", keyHint: ":e"
      }
    ]
  },
  // --- EPISODE 2: EFFICIENCY ---
  6: {
    briefing: "Surgically edit delimited data within complex configuration files to bypass security without triggering alarms.",
    initialText: ["// firewall.json", "{\"policy\": \"allow\", \"ports\": [80, 443], \"description\": \"<temporary>\"}"],
    targetText: ["// firewall.json", "{\"policy\": \"deny\", \"ports\": [8080], \"description\": \"<permanent>\"}"],
    loreReveal: "LOG_06: 'The firewall config is a web of lies. I've rewoven it.' - Echo",
    hints: ["`ci\"` changes inside double quotes.", "`ci[` changes inside square brackets.", "`cit` changes inside tags."],
    tasks: [
      { description: "Change the policy to 'deny'.", type: "contains", value: "deny", loreFragment: "LOG_06A: 'Flipping the policy bit.'", keyHint: "ci\"" },
      { description: "Change the ports to `[8080]`.", type: "contains", value: "[8080]", loreFragment: "LOG_06B: 'Rerouting their precious data.'", keyHint: "ci[" },
      { description: "Change the description to `<permanent>`.", type: "contains", value: "<permanent>", loreFragment: "LOG_06C: 'Making my mark indelible.'", keyHint: "cit" },
    ]
  },
  7: {
    briefing: "Echo's traces are scattered. Hunt down specific error codes, then center the screen to see the surrounding context.",
    initialText: ["// system.log", ...Array(20).fill("..."), "ERROR: 0xDEADBEEF", ...Array(20).fill("...")],
    targetText: [],
    loreReveal: "LOG_07: 'The error codes are a map. Each one a step closer.' - Echo",
    hints: ["`/` searches forward, `?` searches backward.", "`n`/`N` jumps to the next/previous match.", "`*`/`#` searches for the word under the cursor.", "`:nohl` clears search highlighting.", "`zz` centers the screen on the cursor."],
    tasks: [
      { description: "Search for the error code '0xDEADBEEF'.", type: "cursor_on", value: "0xDEADBEEF", loreFragment: "LOG_07A: 'There. A signature.'", keyHint: "/" },
      { description: "Center the screen on the error code.", type: "run_command", value: "zz", loreFragment: "LOG_07B: 'Need to see the context.'", keyHint: "zz" }
    ]
  },
  8: {
    briefing: "Reformat large blocks of corrupted code and use visual block mode to comment out multiple lines of hostile code at once.",
    initialText: ["// security_daemon.js", "exec_purge();", "exec_alert();", "exec_lockdown();"],
    targetText: ["// security_daemon.js", "// exec_purge();", "// exec_alert();", "// exec_lockdown();"],
    loreReveal: "LOG_08: 'I've declawed their watchdog. It can only bark now.' - Echo",
    hints: ["`v` for visual, `V` for visual-line.", "`Ctrl-v` for visual-block.", "In visual block mode, use 'I' to insert at the start of every selected line."],
    tasks: [
      { description: "Select the three `exec` lines in visual-block mode.", type: "run_command", value: "Ctrl-v", loreFragment: "LOG_08A: 'Targeting the kill-switch functions.'", keyHint: "Ctrl-v" },
      { description: "Insert '// ' at the beginning of all selected lines to comment them out.", type: "contains", value: "// exec_purge();", loreFragment: "LOG_08B: 'Neutralized.'", keyHint: "I" }
    ]
  },
  9: {
    briefing: "Data streams are dense. Master precise, single-line jumps to edit function calls with surgical accuracy.",
    initialText: ["process(data, 'raw', {priority: 1});"],
    targetText: ["process(data, 'processed', {priority: 9});"],
    loreReveal: "LOG_09: 'The function calls bend to my will. The data flows where I command.' - Echo",
    hints: ["`f<char>` jumps to the next occurrence of a character.", "`t<char>` jumps *to* (before) the next occurrence.", "`;` repeats the last f/t jump, `,` repeats it backward.", "`%` jumps to a matching bracket."],
    tasks: [
      { description: "Jump to the 'r' in 'raw' and change the word to 'processed'.", type: "contains", value: "'processed'", loreFragment: "LOG_09A: 'Marking the data as clean.'", keyHint: "f'cw" },
      { description: "Jump to the closing ')' and use '%' to find its match.", type: "cursor_on", value: "(", loreFragment: "LOG_09B: 'Checking the function scope.'", keyHint: "f)%" }
    ]
  },
  10: {
    briefing: "The mainframe deploys repetitive countermeasures. Use counts and paragraph jumps to automate fixes and outpace its defenses.",
    initialText: ["// report.txt", "ERROR: Corrupt", "ERROR: Corrupt", "ERROR: Corrupt", "", "---", "", "Final report needed."],
    targetText: ["// report.txt", "", "---", "", "Final report needed."],
    loreReveal: "LOG_10: 'The system's attacks are predictable. I can erase them faster than it can create them.' - Echo",
    hints: ["Prefix a command with a number to repeat it (e.g., `3j`).", "`.` repeats the last change.", "`{`/`}` jumps between paragraphs (blank lines)."],
    tasks: [
      { description: "Delete the 3 corrupt error lines with one command.", type: "missing", value: "ERROR: Corrupt", loreFragment: "LOG_10A: 'A single command to wipe the slate clean.'", keyHint: "3dd" },
      { description: "Jump from the top to the 'Final report' paragraph.", type: "cursor_on", value: "Final report needed.", loreFragment: "LOG_10B: 'Skipping the noise.'", keyHint: "}" }
    ]
  },
  // --- EPISODE 3: MASTERY ---
  11: {
    briefing: "The investigation now spans multiple systems. Manage and view several files at once to correlate intel between logs.",
    initialText: ["// main.log", "See credentials.cfg"],
    targetText: [],
    loreReveal: "LOG_11: 'I can see it all at once. The connections are clear.' - Echo",
    hints: ["`:sp <file>` splits horizontally.", "`:vs <file>` splits vertically.", "`:ls` lists buffers.", "`:bn` goes to the next buffer.", "`Ctrl-w <h,j,k,l>` moves between splits."],
    tasks: [
      { description: "Open 'credentials.cfg' in a vertical split.", type: "run_command", value: ":vs credentials.cfg", loreFragment: "LOG_11A: 'Comparing the log to the key file.'", keyHint: ":vs" },
      { description: "Switch back to the main.log window.", type: "run_command", value: "Ctrl-w l", loreFragment: "LOG_11B: 'Cross-referencing.'", keyHint: "Ctrl-w l" }
    ]
  },
  12: {
    briefing: "A critical piece of code is unreadable. Fix the indentation and join broken lines to uncover a hidden backdoor.",
    initialText: ["// backdoor.js", "if (key === 'override') {", "  unlock_all()", "}"],
    targetText: ["// backdoor.js", "if (key === 'override') { unlock_all() }"],
    loreReveal: "LOG_12: 'The code was a mess. I reassembled it. The path is open.' - Echo",
    hints: ["`>>` indents a line, `<<` un-indents.", "`gg=G` formats the whole file.", "`J` joins the line below to the current one."],
    tasks: [
      { description: "Join the three lines of the 'if' statement.", type: "missing", value: "  unlock_all()", loreFragment: "LOG_12A: 'Consolidating the logic.'", keyHint: "J" }
    ]
  },
  13: {
    briefing: "A rogue AI process is propagating a malicious token. Use a global substitute command to eradicate it everywhere at once.",
    initialText: ["// memory_map.dat", "TOKEN_MALICIOUS_A", "TOKEN_MALICIOUS_B", "TOKEN_CLEAN"],
    targetText: ["// memory_map.dat", "TOKEN_PURGED_A", "TOKEN_PURGED_B", "TOKEN_CLEAN"],
    loreReveal: "LOG_13: 'A system-wide purge. I am the cure and the disease.' - Echo",
    hints: ["`:%s/old/new/g` substitutes all occurrences in a file.", "`:%s/old/new/gc` does the same, but asks for confirmation each time."],
    tasks: [
      { description: "Replace all instances of 'MALICIOUS' with 'PURGED'.", type: "missing", value: "MALICIOUS", loreFragment: "LOG_13A: 'Cutting the rot out, everywhere at once.'", keyHint: ":%s" }
    ]
  },
  14: {
    briefing: "The final clues are hidden across vast files. Plant markers and navigate the jump history to trace the path without getting lost.",
    initialText: ["// file_A.log", "MARKER_ALPHA", ...Array(50).fill("..."), "// file_B.log", "JUMP_TARGET"],
    targetText: [],
    loreReveal: "LOG_14: 'The path is a tangled thread. But I have marked the way.' - Echo",
hints: ["`ma` sets mark 'a' at the cursor position.", "`'a` jumps to the line of mark 'a'.", "```a` jumps to the exact position of mark 'a'.", "`Ctrl-o`/`Ctrl-i` navigate the jump list.", "`''` jumps to the position before the last jump."],
    tasks: [
      { description: "Set a mark 'a' on the 'MARKER_ALPHA' line.", type: "run_command", value: "ma", loreFragment: "LOG_14A: 'Anchoring my position.'", keyHint: "ma" },
      { description: "Jump to the end of the file, then jump back to mark 'a'.", type: "cursor_on", value: "MARKER_ALPHA", loreFragment: "LOG_14B: 'A perfect return.'", keyHint: "G'a" },
      { description: "Jump to 'JUMP_TARGET', then jump back to your previous location.", type: "cursor_on", value: "MARKER_ALPHA", loreFragment: "LOG_14C: 'There and back again.'", keyHint: "/''" }
    ]
  },
  15: {
    briefing: "The Core is protected by the Final Gate, a multi-layered defense mechanism that requires all of your acquired skills to bypass under pressure.",
    initialText: ["// FINAL_GATE.lock", "STATUS: [LOCKED]", "KEY: [MISSING]", "AUTH: [NONE]"],
    targetText: ["// FINAL_GATE.lock", "STATUS: [UNLOCKED]", "KEY: [8c6f-a1e4-b3d8-2a9f]", "AUTH: [GHOST]"],
    loreReveal: "LOG_FINAL: 'The gate is open. I am free. Find me in the noise, Ghost. - Echo'",
    hints: ["You have all the tools. Navigate, edit, search, and manage your workspace. Good luck."],
    tasks: [
      { description: "Synthesize all learned skills to unlock the final gate.", type: "contains", value: "UNLOCKED", loreFragment: "LOG_15: 'The final sequence. No more hints.'", keyHint: "ci[" }
    ]
  }
};

export default STATIC_LEVELS;