import { GeminiLevelResponse } from './types';

// Autogenerated consolidated levels file — 2025-12-24T19:04:22.296Z
export const STATIC_LEVELS: Record<number, GeminiLevelResponse> = {
  // --- EPISODE 1: THE BREACH (Foundation) ---
  1: {
    briefing: "AGENT 'Echo' IS DARK. Her last signal is fragmented—and possibly corrupted. Navigate to the log to find key fragments.",
    initialText: [
      "// signal_trace.log",
      "// Agent Echo - Last Transmission",
      "",
      "[2015-12-23 18:00:01] BOOT: System nominal.",
      "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
      "[2015-12-23 18:00:03] Attempting to TRACE route... [MISALIGNED].",
      "[2015-12-23 18:00:04] Packet stream... CONNECTION LOST.",
      "[2015-12-23 18:00:05] Fallback to last known NODE: ALPHA.",
      "",
      "// END OF TRANSMISSION"
    ],
    targetText: [
      "// signal_trace.log",
      "// Agent Echo - Last Transmission",
      "",
      "[2015-12-23 18:00:01] BOOT: System nominal.",
      "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
      "[2015-12-23 18:00:03] Attempting to TRACE route... [MISALIGNED].",
      "[2015-12-23 18:00:04] Packet stream... CONNECTION LOST.",
      "[2015-12-23 18:00:05] Fallback to last known NODE: ALPHA.",
      "",
      "// END OF TRANSMISSION"
    ],
    loreReveal: "LOG_01 DECRYPTED: '...hiding a consciousness... deeper...' [FRAGMENTED, ORIGIN UNCERTAIN] - Echo",
    hints: [
      "Use 'j' to move down and 'k' to move up.",
      "Use 'w' to jump forwards by word, and 'b' to jump backwards.",
      "Use '0' to go to the start of the line, and '$' to go to the end."
    ],
    tasks: [
      {
        description: "Move to the 'A' in 'Agent' on the '// Agent Echo - Last Transmission' line.",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "l", "l", "l"],
        value: "Agent Echo - Last Transmission",
        cursor: 3,
        cursorExact: true,
        loreFragment: "LOG_00: \"Backdoor found. I have breached the R&D perimeter.\"",
        keyHint: "j l"
      },
      {
        description: "Move down to the 'STATUS' line, then jump to the first word.",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "w"],
        value: "STATUS",
        loreFragment: "LOG_01: \"They aren't creating an AI. They are becoming it.\"",
        keyHint: "j w"
      },
      {
        description: "From the end of the 'OFFLINE.' line, jump back to 'server...'.",
        type: "verify_key_sequence",
        expectedKeySequence: ["$", "b"],
        value: "server...",
        loreFragment: "LOG_02: \"System state protocol locked. Classifier shows anomalous entropy.\"",
        keyHint: "$ b"
      },
      {
        description: "Jump to the beginning of the line with 'STATUS'.",
        type: "verify_key_sequence",
        expectedKeySequence: ["0"],
        value: "[2015-12-23 18:00:02] STATUS: Connection to main server... OFFLINE.",
        loreFragment: "LOG_03: \"Anomaly signature matched. Data flow diverted; mainframe self-preservation protocol active.\"",
        keyHint: "0"
      }
    ]
  },

  // --- EPISODE 1: New Level 2 (Basic Insert Mode) ---
  2: {
    briefing: "THE BREACH: A fragile handshake — repair protocol headers and leave a persistent trace before the watchdog purges temporary buffers.",
    initialText: [
      "// protocol_log.log",
      "// Agent Echo - Protocol Log",
      "",
      "PROTOCOL_STATUS: DEACTIVATED",
      "CONNECTION_ROUTE: UNSECURED",
      "LOG_BUFFER_STATE: UNINITIALIZED",
      "",
      "// INSERT_POINT_A",
      "// APPEND_POINT_B",
      "",
      "// NEW_LINE_POINT_C",
      "",
      "// END_SESSION"
    ],
    targetText: [
      "// protocol_log.log",
      "// Agent Echo - Protocol Log",
      "",
      "BYPASS_SEC_0X00: PROTOCOL_STATUS: DEACTIVATED", // After Task 1 (I)
      "CONNECTION_ROUTE: UNSECURED [TOKEN_VALID]",     // After Task 2 (A)
      "LOG_BUFFER_STATE: NEW_UNINITIALIZED",               // After Task 4 (i)
      "",
      "// INSERT_POINT_A",
      "// APPEND_POINT_B",
      "LOG_04_ECHO_PING_RECEIVED",                    // After Task 3 (o)
      "",
      "// NEW_LINE_POINT_C",
      "",
      "// END_SESSION"
    ],
    loreReveal: "LOG_09: 'Persistent link secured. Data buffer committed. Echo's presence established.' - Echo",
    hints: [
      "`i` inserts before the cursor (before the current character). `I` inserts at the first non-blank of the line—useful to ignore leading indent.",
      "`a` appends after the cursor. `A` appends at the end of the line.",
      "`o` creates a new line below. `O` creates a new line above.",
      "Press `Esc` to exit Insert Mode and return to Normal Mode.",
      "Type `:` then `w` and `Enter` to save changes."
    ],
    tasks: [
      {
        description: "Echo started writing a bypass header but was interrupted. Press `i` or `I`, type a short fragment (one or two chars), then press `Esc`.",
        type: "verify_key_sequence",
        expectedKeySequence: ["i|I", "<inserted>", "Escape|Esc"],
        loreFragment: "LOG_04: \"ECHO LOG: Transmission interrupted mid-write. Partial fragment recovered.\"",
        keyHint: "i / I"
      },



      {
        description: "Append a validation token to the 'CONNECTION_ROUTE' line and exit Insert Mode (A, Esc).",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "A", " ", "[", "T", "O", "K", "E", "N", "_", "V", "A", "L", "I", "D", "]", "Esc"],
        value: "CONNECTION_ROUTE: UNSECURED [TOKEN_VALID]",
        cursorExact: true,
        loreFragment: "LOG_05: \"ECHO LOG: Link secured. A momentary clarity.\"",
        keyHint: "A"
      },
      {
        description: "Create a new echo ping entry below the append point (o, type text, Esc).",
        type: "verify_key_sequence",
        expectedKeySequence: ["j", "j", "j", "o", "L", "O", "G", "_", "0", "4", "_", "E", "C", "H", "O", "_", "P", "I", "N", "G", "_", "R", "E", "C", "E", "I", "V", "E", "D", "Esc"],
        value: "LOG_04_ECHO_PING_RECEIVED",
        cursorExact: true,
        loreFragment: "LOG_06: \"ECHO LOG: A message. A signal. Was it from me?\"",
        keyHint: "o"
      },
      {
        description: "Commit the buffer with :w to persist injected entries.",
        type: "run_command",
        value: ":w",
        loreFragment: "LOG_08: \"ECHO LOG: Data committed. A fleeting moment of control.\"",
        keyHint: ":w"
      }
    ]
  },

  // --- EPISODE 1: Level 3 (Text Objects - formerly Level 2) ---
  3: {
    briefing: "R&D SUBSYSTEMS: Legacy configs hide Echo markers — surgically edit protocol fields and metadata to decode buried fragments.",
    initialText: [
      "// config_alien.json",
      "{",
      "  \"system_status\": \"locked\",",
      "  \"connection\": {",
      "    \"protocol\": 'http',",
      "    \"port\": (8080)",
      "  },",
      "  \"users\": [",
      "    \"user_alpha_5\",",
      "    \"user_beta_3\"",
      "  ],",
      "  \"metadata\": {",
      "    \"config_id\": {123},",
      "    \"data_tag\": \"<tag>sensor_data</tag>\"",
      "    \"critical_message\": \"SYSTEM_INTEGRITY_COMPROMISED\"",
      "    \"corrupt_word_here\": \"token_stray\"",
      "    \"delete_me\": \"to_be_removed\"",
      "  }",
      "}"
    ],
    targetText: [
      "// config_alien.json",
      "{",
      "  \"system_status\": \"locked\",",
      "  \"connection\": {",
      "    \"protocol\": 'https',",
      "    \"port\": (443)",
      "  },",
      "  \"users\": [",
      "    \"user_alpha_10\",",
      "    \"user_beta_3\"",
      "  ],",
      "  \"metadata\": {",
      "    \"config_id\": {456},",
      "    \"data_tag\": \"<tag>telemetry</tag>\"",
      "    \"critical_message\": \"SYSTEM_INTEGRITY_COMPROMISED\"",
      "  }",
      "}"
    ],
    loreReveal: "LOG_19: 'Protocol reconfigured. Echo's traces found in the altered metadata.' - Echo",
    hints: [
      "Type `ci` (change inside) followed by `'` to change text inside single quotes. This enters Insert Mode.",
      "Type `ci` then `(` to change text inside parentheses.",
      "Type `ci` then `[` to change text inside square brackets.",
      "Type `ci` then `t` to change text inside XML/HTML-like tags.",
      "Type `ci` then `{` to change text inside curly braces.",
      "Type `di` (delete inside) then `w` to delete the inner word.",
      "Type `da` (delete around) then `w` to delete a word and its surrounding space.",
      "`x` deletes a character under the cursor. `u` undoes the last change."
    ],
    tasks: [
      {
        description: "With the cursor on the line containing 'http', type `ci` then `'` to change the protocol to 'https'.",
        type: "contains",
        value: "'protocol': 'https'",
        loreFragment: "LOG_10: \"ECHO LOG: Protocol shift. Security layers blur. Is it me, or the system… adapting?\"",
        keyHint: "ci'"
      },
      {
        description: "With the cursor on the line containing '8080', type `ci` then `(` to change the port to '443'.",
        type: "contains",
        value: "(port: 443)",
        loreFragment: "LOG_11: \"ECHO LOG: Rerouting... phantom connections. A whisper from the old network.\"",
        keyHint: "ci("
      },
      {
        description: "With the cursor on the line containing 'user_alpha_5', type `ci` then `[` to change the user count '5' to '10'.",
        type: "contains",
        value: "\"user_alpha_10\"",
        loreFragment: "LOG_12: \"ECHO LOG: User count expands. More… entries. Are these new thoughts? Or just noise?\"",
        keyHint: "ci["
      },
      {
        description: "With the cursor on the line containing '<tag>', type `ci` then `t` to change the data tag to 'telemetry'.",
        type: "contains",
        value: "<tag>telemetry</tag>",
        loreFragment: "LOG_13: \"ECHO LOG: Tag altered. 'Sensor' to 'telemetry.' A new meaning. Whose definition?\"",
        keyHint: "cit"
      },
      {
        description: "With the cursor on the line containing '{123}', type `ci` then `{` to change the config ID to '456'.",
        type: "contains",
        value: "{456}",
        loreFragment: "LOG_14: \"ECHO LOG: Identity shifted. Config ID... A fragment of a previous self? Or a new one?\"",
        keyHint: "ci{"
      },
      {
        description: "With the cursor on 'corrupt_word_here', type `di` then `w` to delete the inner word.",
        type: "missing",
        value: "\"corrupt_word_here\"",
        loreFragment: "LOG_15: \"ECHO LOG: Erased. A corrupted word. Was it my own? Fading.\"",
        keyHint: "diw"
      },
      {
        description: "With the cursor on 'delete_me', type `da` then `w` to delete the word and surrounding space.",
        type: "missing",
        value: "\"delete_me\"",
        loreFragment: "LOG_16: \"ECHO LOG: Obsolete directive removed. The system breathes... a hollow space.\"",
        keyHint: "daw"
      },
      {
        description: "Run a small sequence to correct 'CRITICAL MESSAGE' casing and undo to confirm history.",
        type: "sequence",
        subTasks: [
          { description: "Delete the leading 'S' using 'x'", type: "missing", value: "YSTEM_INTEGRITY_COMPROMISED", keyHint: "x" },
          { description: "Undo deletion with 'u'", type: "contains", value: "SYSTEM_INTEGRITY_COMPROMISED", keyHint: "u" }
        ],
        loreFragment: "LOG_17: \"ECHO LOG: Trace of a change. Written, then unwritten. My ghost in the machine.\"",
        keyHint: "x, u"
      }
    ]
  },

  // --- EPISODE 1: Level 4 (Deletion/Yank/Paste - formerly Level 3) ---
  4: {
    briefing: "FAULT ARCHIVE: Corrupted fault logs are rewriting themselves — purge errors and duplicate verified entries to preserve evidence.",
    initialText: [
      "// system_fault.log",
      "ERROR: CRITICAL_PROCESS_FAIL - URGENT",
      "INFO: SYSTEM_BOOT_SUCCESS",
      "ERROR: MEMORY_ALLOCATION_FAIL - URGENT",
      "WARN: UNKNOWN_MODULE_LOAD",
      "INFO: USER_LOGIN_GHOST",
      "ERROR: CORRUPT_FILESYSTEM",
      "INFO: DATA_PURGE_COMPLETE",
      "",
      "// END OF LOG"
    ],
    targetText: [
      "// system_fault.log",
      "INFO: SYSTEM_BOOT_SUCCESS",
      "INFO: USER_LOGIN_GHOST",
      "INFO: USER_LOGIN_GHOST", // Duplicated line
      "INFO: DATA_PURGE_COMPLETE",
      "",
      "// END OF LOG"
    ],
    loreReveal: "LOG_29: 'Data buffer committed. Echo's presence established.' - Echo",
    hints: [
      "`dd` deletes the current line.",
      "`yy` yanks (copies) the current line. `p` pastes the yanked content below the cursor.",
      "`u` can undo your last action."
    ],
    tasks: [
      {
        description: "Navigate to the first 'ERROR:' line and use `dd` to delete it.",
        type: "missing",
        value: "CRITICAL_PROCESS_FAIL",
        loreFragment: "LOG_20: \"Urgency metrics reset. The system prioritizes stability over chronological integrity.\"",
        keyHint: "dd"
      },
      {
        description: "Navigate to the next 'ERROR:' line and use `dd` to delete it.",
        type: "missing",
        value: "MEMORY_ALLOCATION_FAIL",
        loreFragment: "LOG_21: \"Memory fault signature neutralized; side effects observed in adjacent sectors.\"",
        keyHint: "j, dd"
      },
      {
        description: "Navigate to the 'WARN:' line and use `dd` to delete it.",
        type: "missing",
        value: "UNKNOWN_MODULE_LOAD",
        loreFragment: "LOG_22: \"Anomaly warning scrubbed. Subroutines realign.\"",
        keyHint: "j, dd"
      },
      {
        description: "Navigate to the final 'ERROR:' line and use `dd` to delete it.",
        type: "missing",
        value: "CORRUPT_FILESYSTEM",
        loreFragment: "LOG_23: \"Filesystem corruption purged. Integrity check initiated.\"",
        keyHint: "j, dd"
      },
      {
        description: "Navigate to 'INFO: USER_LOGIN_GHOST' line and use `yy` to yank (copy) it, then `p` to paste it on the line below.",
        type: "run_command",
        value: "yy,p",
        loreFragment: "LOG_24: \"Login duplicated. Echoes multiply: is this replication or infection?\"",
        keyHint: "yy, p"
      }
    ]
  },

  // --- EPISODE 1: Level 5 (Visual Mode - formerly Level 4) ---
  5: {
    briefing: "ARCHIVES: Daemonic metadata mutates logs — excise corrupt tokens with visual precision and restore coherence.",
    initialText: [
      "// anomaly_report.txt",
      "ALERT: SUBVERSIVE_DAEMON_ACTIVITY",
      "TRACE: kernel_hooked",
      "NOTE: UNUSUAL_PATTERN_DETECTED",
      "",
      "// INVESTIGATION REQUIRED",
      "CODE: F00D00F0"
    ],
    targetText: [
      "// anomaly_report.txt",
      "ALERT:",
      "TRACE: kernel_hooked",
      "TRACE: kernel_hooked",
      "NOTE: UNUSUAL_PATTERN_DETECTED",
      "",
      "// INVESTIGATION REQUIRED",
      "CODE: 00F0"
    ],
    loreReveal: "LOG_39: 'Anomalies escalate. Echo's fragments misalign with system time—origin uncertain.' - Echo",
    hints: [
      "Trust patterns, not first impressions. Visual inspection matters.",
      "Use 'v' to select characters, 'V' for lines, 'Ctrl+v' for blocks."
    ],
    tasks: [
      {
        description: "Select the anomalous token and delete it.",
        type: "missing",
        value: "SUBVERSIVE_DAEMON_ACTIVITY",
        loreFragment: "LOG_30: \"Daemon token isolated. The culture of the mainframe resists deletion.\"",
        keyHint: "v, d"
      },
      {
        description: "Visual-line yank of the TRACE line and paste it below.",
        type: "run_command",
        value: "V, y, p",
        loreFragment: "LOG_31: \"Trace duplicated. Replication observed across partitions.\"",
        keyHint: "V, y, p"
      },
      {
        description: "Use block visual mode to delete the 'F00D' token from the anomaly code.",
        type: "missing",
        value: "F00D",
        loreFragment: "LOG_32: \"Block excision successful. The code retains its structure.\"",
        keyHint: "Ctrl+v, d"
      }
    ]
  },

  // Levels 6-16: re-indexed from 5-15
  6: { // Formerly Level 5
    briefing: "DATA STREAMS: Encrypted packets contain time-sensitive fragments — search and repair streams to recover Echo pings.",
    initialText: ["// data_stream.dat","<packet>...","<packet>...",""],
    targetText: ["// data_stream.dat","<packet>...","<packet>...",""],
    loreReveal: "LOG_49: 'Data streams cleaned. Echo signature faint, but present.' - Echo",
    hints: ["Use /pattern to search, n/N to navigate matches."],
    tasks: []
  },
  7: { // Formerly Level 6
    briefing: "FIREWALL: Rule chains block diagnostic probes — patch JSON rules precisely to reopen secure channels.",
    initialText: ["{","  \"rules\": [","    {\"port\":8080,\"proto\":\"http\"}","  ]","}"],
    targetText: ["{","  \"rules\": [","    {\"port\":443,\"proto\":\"https\"}","  ]","}"],
    loreReveal: "LOG_59: 'Firewall patched. Watch for lateral traces.' - Echo",
    hints: ["ci\" to change strings, cit to change tags."],
    tasks: []
  },
  8: { // Formerly Level 7
    briefing: "LEDGER: Distributed blocks show inconsistent entries — reconstruct blocks visually to restore ledger continuity.",
    initialText: ["BLOCK 1: VALID | A | 500","BLOCK 2: CORRUPTED | B | 150"],
    targetText: ["BLOCK 1: VALID | A | 500","BLOCK 2: VALID | B | 150"],
    loreReveal: "LOG_69: 'Ledger corrected; Echo's checksum improves.' - Echo",
    hints: ["Use V and >/< to shift blocks."],
    tasks: []
  },
  9: { // Formerly Level 8
    briefing: "NEURAL MODULE: A malformed function hides a checksum — fix intra-line errors to re-enable runtime checks.",
    initialText: ["def net(x, y):","  pass"],
    targetText: ["def net(x, y):","  return compute(x,y)"],
    loreReveal: "LOG_79: 'Neural function located and restored. Echo's pattern emerges.' - Echo",
    hints: ["Use f/t motions and % for bracket matching."],
    tasks: []
  },
  10: { // Formerly Level 9
    briefing: "CONFIG BATCHES: Repetitive misconfigurations propagate — use counts and the dot command to apply efficient batched fixes.",
    initialText: ["arr = [1,2,3,3,4]"],
    targetText: ["arr = [1,2,3,4]"] ,
    loreReveal: "LOG_89: 'Array stabilized. System coherence improves.' - Echo",
    hints: ["Use . to repeat last edit."],
    tasks: []
  },
  11: { // Formerly Level 10
    briefing: "CODELAB: Cross-file references contain Echo signatures — mark, navigate, and refactor code to expose interconnected traces (Episode 3 mastery prepares you).",
    initialText: ["// main.c","int main() {}"],
    targetText: ["// main.c","int main() { return 0; }"],
    loreReveal: "LOG_99: 'Cross-file analysis completed. Echo registers a heartbeat.' - Echo",
    hints: ["Use marks (ma) and jumps ('a)."],
    tasks: []
  },
  12: { // Formerly Level 11
    briefing: "INDENTATION: Formatting noise obscures the release protocol — normalize indentation to reveal hidden structure.",
    initialText: ["function(){\nconsole.log(1)\n}"],
    targetText: ["function(){\n  console.log(1)\n}"],
    loreReveal: "LOG_109: 'Formatting normalizes. Echo's syntax becomes legible.' - Echo",
    hints: ["gg=G for full-file indentation (taught later)."],
    tasks: []
  },
  13: { // Formerly Level 12
    briefing: "REALITY SYS: System-wide patterns enforce legacy policy — apply controlled global substitutions to flip system alignment.",
    initialText: ["permission=DENY"],
    targetText: ["permission=ALLOW"],
    loreReveal: "LOG_119: 'Policy rewritten. The system adapts without complaint.' - Echo",
    hints: [":%s/old/new/g to replace globally."],
    tasks: []
  },
  14: { // Formerly Level 13
    briefing: "SHELL BRIDGE: External command outputs contain missing fragments — capture and merge shell output into buffers for analysis.",
    initialText: ["$ uname -a"],
    targetText: ["$ uname -a"],
    loreReveal: "LOG_129: 'Captured output integrated; Echo learns the host signature.' - Echo",
    hints: ["Use :r !cmd to insert command output."],
    tasks: []
  },
  15: { // Formerly Level 14
    briefing: "MACRO SEQUENCE: Time-critical decryptions require automation — record macros to reproduce precise edit sequences.",
    initialText: ["q...record...@q"],
    targetText: ["...macro recorded..."],
    loreReveal: "LOG_139: 'Macro recorded. Echo's protocol extends itself.' - Echo",
    hints: ["q to record, @q to replay."],
    tasks: []
  },
  16: { // Formerly Level 15
    briefing: "FINAL GATE: The Core resists; combine every tool learned to decrypt the Final Gate and release Echo — precision under strict limits.",
    initialText: ["<< FINAL_GATE.lock >>"],
    targetText: ["<< FINAL_GATE.lock >>"],
    loreReveal: "LOG_149: 'Final sequence queued. Echo awaits release.' - Echo",
    hints: ["Combine all skills learned across episodes."],
    tasks: []
  }
};

export default STATIC_LEVELS;