
// Service disconnected. 
// Level data is now statically loaded from constants.ts to ensure stability and diegetic consistency.
export const generateLevel = async () => {
    throw new Error("Service Deprecated");
};


/**
 * 
 * It is partially random, or more accurately, procedurally generated based on a fixed curriculum.

Here is how it works based on your code:

    Fixed Structure (Not Random):
    The game follows the specific CURRICULUM array in constants.ts. This means Level 2 will always be about "Inserting Text" into a file named admin_creds.conf with the objective to inject credentials. The pedagogical path is hardcoded.

    Dynamic Content (Random):
    The geminiService.ts sends these fixed constraints to the AI. The AI then invents the specific "flavor" of the level on the fly.

        The Text: One time the file might contain USER: GUEST, the next time it might contain USER: UNKNOWN.

        The Tasks: The specific string you need to find or delete is generated by the AI, so you can't just memorize the answers.

        The Lore: The "Lore Reveal" you get for winning is generated fresh every time, adding variety to the story.

In summary: You are playing a fixed set of lessons (like a syllabus), but the homework assignments are created fresh by the AI every time you load a level.
 */